
export const ChecklistItems = [
  { id: 1, text: "👶Be born", isChecked: false },
  { id: 2, text: "🚶Take first steps", isChecked: false },
  { id: 3, text: "🔊Say first word", isChecked: false },
  { id: 4, text: "📖Learn a read", isChecked: false },
  { id: 5, text: "🤗Make a friend", isChecked: false },
  { id: 6, text: "🚴‍♀️Learn to ride a bike", isChecked: false },
  { id: 7, text: "📕Read a book", isChecked: false },
  { id: 8, text: "🏊Learn to swim", isChecked: false },
  { id: 9, text: "🏫Finish elementary school", isChecked: false },
  { id: 10, text: "🏏Play a sport", isChecked: false },
  { id: 11, text: "✈️Fly in a plane", isChecked: false },
  { id: 12, text: "🚤Ride a boat", isChecked: false },
  { id: 13, text: "🚄Travel by train", isChecked: false },
  { id: 14, text: "🚁Get on a helicopter", isChecked: false },
  { id: 15, text: "🌊See the ocean", isChecked: false },
  { id: 16, text: "❄️See snow", isChecked: false },
  { id: 17, text: "⛄Make a snowman", isChecked: false },
  { id: 18, text: "🏫Finish middle school", isChecked: false },
  { id: 19, text: "🎶Go to a concert", isChecked: false },
  { id: 20, text: "🎸Play an instrument", isChecked: false },
  { id: 21, text: "🚗Start driving", isChecked: false },
  { id: 22, text: "🗣️Give a speech", isChecked: false },
  { id: 23, text: "💰Invest some money", isChecked: false },
  { id: 24, text: "🏆Win a trophy", isChecked: false },
  { id: 25, text: "🍳Learn to cook", isChecked: false },
  { id: 26, text: "🎓Graduate college", isChecked: false },
  { id: 27, text: "📝Sign a contract", isChecked: false },
  { id: 28, text: "🏕️Go camping", isChecked: false },
  { id: 29, text: "🎢Ride a rollercoaster", isChecked: false },
  { id: 30, text: "💋Get kissed", isChecked: false },
  { id: 31, text: "💳Get a credit card", isChecked: false },
  { id: 32, text: "🛣️Go on a road trip", isChecked: false },
  { id: 33, text: "🌍Visit another country", isChecked: false },
  { id: 34, text: "🗣️Learn another language", isChecked: false },
  { id: 35, text: "😓Make a terrible mistake", isChecked: false },
  { id: 36, text: "🏃Run a marathon", isChecked: false },
  { id: 37, text: "🌋See a volcano", isChecked: false },
  { id: 38, text: "📈Get promoted", isChecked: false },
  { id: 39, text: "🥀Get dumped", isChecked: false },
  { id: 40, text: "🧑‍💼 Get a job", isChecked: false },
  { id: 41, text: "🧗Climb a mountain", isChecked: false },
  { id: 42, text: "🌌Explore a cave", isChecked: false },
  { id: 43, text: "💕Have a long relationship", isChecked: false },
  { id: 44, text: "📜Graduate high school", isChecked: false },
  { id: 45, text: "🌟Meet an idol", isChecked: false },
  { id: 46, text: "💵Get a paycheck", isChecked: false },
  { id: 47, text: "🔥Get fired", isChecked: false },
  { id: 48, text: "📰Get in the news", isChecked: false },
  { id: 49, text: "🗳️Vote in an election", isChecked: false },
  { id: 50, text: "🎭Switch careers", isChecked: false },
  { id: 52, text: "🏡Buy a house", isChecked: false },
  { id: 53, text: "💍Get engaged", isChecked: false },
  { id: 54, text: "👰Get married", isChecked: false },
  { id: 55, text: "👶Have a kid", isChecked: false },
  { id: 56, text: "🚶Teach your kid to walk", isChecked: false },
  { id: 57, text: "🗣️Teach your kid to talk", isChecked: false },
  { id: 58, text: "🎓Watch your kid graduate", isChecked: false },
  { id: 59, text: "👰Watch your kid get married", isChecked: false },
  { id: 60, text: "👴Become a grandparent", isChecked: false },
  { id: 61, text: "🏖️Retire", isChecked: false },
  { id: 62, text: "📖Tell your grandkid a story", isChecked: false },
  { id: 63, text: "🌞See a solar eclipse", isChecked: false },
  { id: 64, text: "🌷Plant a garden", isChecked: false },
  { id: 65, text: "🌍Travel the world", isChecked: false },
  { id: 66, text: "🎂Turn 100", isChecked: false },
  { id: 67, text: "✅Complete Life Checklist", isChecked: false }
];